// @routes-hash 8f08740627174e9e1869cb8c4c80c797
import { Express } from "express";

import route1 from "./routes/artStyle/getArtStyle";
import route2 from "./routes/novel/addNovel";
import route3 from "./routes/novel/clearNovel";
import route4 from "./routes/novel/delNovel";
import route5 from "./routes/novel/getNovel";
import route6 from "./routes/novel/updateNovel";
import route7 from "./routes/other/clearDatabase";
import route8 from "./routes/other/deleteAllData";
import route9 from "./routes/other/getCaptcha";
import route10 from "./routes/other/login";
import route11 from "./routes/other/testAI";
import route12 from "./routes/other/testImage";
import route13 from "./routes/other/testVideo";
import route14 from "./routes/project/addProject";
import route15 from "./routes/project/delProject";
import route16 from "./routes/project/getProject";
import route17 from "./routes/project/getProjectCount";
import route18 from "./routes/project/getSingleProject";
import route19 from "./routes/project/updateProject";
import route20 from "./routes/script/addScript";
import route21 from "./routes/script/delScript";
import route22 from "./routes/script/getScrptApi";
import route23 from "./routes/script/updateScript";
import route24 from "./routes/task/getMyTaskApi";
import route25 from "./routes/task/getTaskCategories";
import route26 from "./routes/task/taskDetails";
import route27 from "./routes/user/getUser";
import route28 from "./routes/user/saveUser";

export default async (app: Express) => {
  app.use("/artStyle/getArtStyle", route1);
  app.use("/novel/addNovel", route2);
  app.use("/novel/clearNovel", route3);
  app.use("/novel/delNovel", route4);
  app.use("/novel/getNovel", route5);
  app.use("/novel/updateNovel", route6);
  app.use("/other/clearDatabase", route7);
  app.use("/other/deleteAllData", route8);
  app.use("/other/getCaptcha", route9);
  app.use("/other/login", route10);
  app.use("/other/testAI", route11);
  app.use("/other/testImage", route12);
  app.use("/other/testVideo", route13);
  app.use("/project/addProject", route14);
  app.use("/project/delProject", route15);
  app.use("/project/getProject", route16);
  app.use("/project/getProjectCount", route17);
  app.use("/project/getSingleProject", route18);
  app.use("/project/updateProject", route19);
  app.use("/script/addScript", route20);
  app.use("/script/delScript", route21);
  app.use("/script/getScrptApi", route22);
  app.use("/script/updateScript", route23);
  app.use("/task/getMyTaskApi", route24);
  app.use("/task/getTaskCategories", route25);
  app.use("/task/taskDetails", route26);
  app.use("/user/getUser", route27);
  app.use("/user/saveUser", route28);
}
