// @routes-hash bf7da66ccf67db60a70132433ee2879f
import { Express } from "express";

import route1 from "./routes/artStyle/getArtStyle";
import route2 from "./routes/assets/addAssets";
import route3 from "./routes/assets/batchDelete";
import route4 from "./routes/assets/batchGenerationData";
import route5 from "./routes/assets/delAssets";
import route6 from "./routes/assets/generateAssets";
import route7 from "./routes/assets/getAssetsApi";
import route8 from "./routes/assets/getImage";
import route9 from "./routes/assets/polishAssetsPrompt";
import route10 from "./routes/assets/saveAssets";
import route11 from "./routes/assets/updateAssets";
import route12 from "./routes/other/clearDatabase";
import route13 from "./routes/other/deleteAllData";
import route14 from "./routes/other/getCaptcha";
import route15 from "./routes/other/login";
import route16 from "./routes/other/testAI";
import route17 from "./routes/other/testImage";
import route18 from "./routes/other/testVideo";
import route19 from "./routes/project/addProject";
import route20 from "./routes/project/delProject";
import route21 from "./routes/project/getProject";
import route22 from "./routes/project/getProjectCount";
import route23 from "./routes/project/getSingleProject";
import route24 from "./routes/project/updateProject";
import route25 from "./routes/script/addScript";
import route26 from "./routes/script/delScript";
import route27 from "./routes/script/getScrptApi";
import route28 from "./routes/script/updateScript";
import route29 from "./routes/task/getMyTaskApi";
import route30 from "./routes/task/getTaskCategories";
import route31 from "./routes/task/taskDetails";
import route32 from "./routes/user/getUser";
import route33 from "./routes/user/saveUser";

export default async (app: Express) => {
  app.use("/artStyle/getArtStyle", route1);
  app.use("/assets/addAssets", route2);
  app.use("/assets/batchDelete", route3);
  app.use("/assets/batchGenerationData", route4);
  app.use("/assets/delAssets", route5);
  app.use("/assets/generateAssets", route6);
  app.use("/assets/getAssetsApi", route7);
  app.use("/assets/getImage", route8);
  app.use("/assets/polishAssetsPrompt", route9);
  app.use("/assets/saveAssets", route10);
  app.use("/assets/updateAssets", route11);
  app.use("/other/clearDatabase", route12);
  app.use("/other/deleteAllData", route13);
  app.use("/other/getCaptcha", route14);
  app.use("/other/login", route15);
  app.use("/other/testAI", route16);
  app.use("/other/testImage", route17);
  app.use("/other/testVideo", route18);
  app.use("/project/addProject", route19);
  app.use("/project/delProject", route20);
  app.use("/project/getProject", route21);
  app.use("/project/getProjectCount", route22);
  app.use("/project/getSingleProject", route23);
  app.use("/project/updateProject", route24);
  app.use("/script/addScript", route25);
  app.use("/script/delScript", route26);
  app.use("/script/getScrptApi", route27);
  app.use("/script/updateScript", route28);
  app.use("/task/getMyTaskApi", route29);
  app.use("/task/getTaskCategories", route30);
  app.use("/task/taskDetails", route31);
  app.use("/user/getUser", route32);
  app.use("/user/saveUser", route33);
}
